server:
  port: 8020
spring:
  datasource:
#  mysql 192.168.33.2
    url: jdbc:mysql://mysql:3306/anomalous?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: hadoop
    driver-class-name: com.mysql.cj.jdbc.Driver

  #kafka配置
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      bootstrap-servers: localhost:9092
      enable-auto-commit: true
      group-id: applog
      auto-offset-reset: latest
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#   #kafka配置
#  kafka:
#   consumer:
#     enable-auto-commit: true
#     group-id: applog
#     auto-offset-reset: latest
#     bootstrap-servers: localhost:9092

eureka:
  client:
    service-url:
      defalutZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.changhong.entity