server:
  port: 8010
spring:
  datasource:
    url: jdbc:mysql://192.168.33.2:3306/anomalous?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: hadoop
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defalutZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.changhong.entity